name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  modal_side_sheet: ^0.0.1
  
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: YandexSansText
      fonts:
        - asset: assets/fonts/YandexSansText-Regular.ttf
          weight: 400
        - asset: assets/fonts/YandexSansText-Bold.ttf
          weight: 700
        - asset: assets/fonts/YandexSansText-Light.ttf
          weight: 300
        - asset: assets/fonts/YandexSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/YandexSansText-Thin.ttf
          weight: 100
        - asset: assets/fonts/YandexSansText-RegularItalic.ttf
          weight: 400
          style: italic

  # Ассеты для изображений роботов
  assets:
    - assets/images/