"""Create tasks table

Revision ID: 0002
Revises: 0001
Create Date: 2024-01-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type for task types
    task_type_enum = sa.Enum('route', 'carpet', 'demo', 'custom', name='tasktype')
    task_type_enum.create(op.get_bind())
    
    # Create tasks table
    op.create_table('tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shift_id', sa.Integer(), nullable=False),
        sa.Column('executor', sa.Integer(), nullable=False),
        sa.Column('robot_name', sa.Integer(), nullable=False),
        sa.Column('transport_id', sa.Integer(), nullable=True),
        sa.Column('time_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('time_end', sa.DateTime(timezone=True), nullable=False),
        sa.Column('type', task_type_enum, nullable=False),
        sa.Column('geojson', sa.JSON(), nullable=True),
        sa.Column('tickets', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['executor'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
        sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    
    # Drop enum type
    task_type_enum = sa.Enum('route', 'carpet', 'demo', 'custom', name='tasktype')
    task_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
