"""Update shifts table structure

Revision ID: 0003
Revises: 0002
Create Date: 2024-01-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key constraints and columns
    op.drop_constraint('shifts_ibfk_1', 'shifts', type_='foreignkey')
    
    # Drop old columns
    op.drop_column('shifts', 'executor')
    op.drop_column('shifts', 'robot')
    op.drop_column('shifts', 'transport_name')
    op.drop_column('shifts', 'route')
    op.drop_column('shifts', 'carpet')
    op.drop_column('shifts', 'geojson')
    
    # Add new columns
    op.add_column('shifts', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('shifts', sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Update existing records to have a default date (you may want to adjust this)
    op.execute("UPDATE shifts SET date = time_start WHERE date IS NULL")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new columns
    op.drop_column('shifts', 'edited_at')
    op.drop_column('shifts', 'date')
    
    # Add back old columns
    op.add_column('shifts', sa.Column('executor', sa.String(200), nullable=False))
    op.add_column('shifts', sa.Column('robot', sa.Integer(), nullable=False))
    op.add_column('shifts', sa.Column('transport_name', sa.String(200), nullable=True))
    op.add_column('shifts', sa.Column('route', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('carpet', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('geojson', sa.JSON(), nullable=True))
    
    # Add back foreign key constraint
    op.create_foreign_key('shifts_ibfk_1', 'shifts', 'robots', ['robot'], ['id'])
    
    # ### end Alembic commands ###
