"""Fix task type enum case

Revision ID: 0004
Revises: 0003
Create Date: 2024-01-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update enum values to uppercase
    op.execute("ALTER TABLE tasks MODIFY COLUMN type ENUM('ROUTE','CARPET','DEMO','CUSTOM') NOT NULL")
    
    # Update existing data to uppercase
    op.execute("UPDATE tasks SET type = 'ROUTE' WHERE type = 'route'")
    op.execute("UPDATE tasks SET type = 'CARPET' WHERE type = 'carpet'")
    op.execute("UPDATE tasks SET type = 'DEMO' WHERE type = 'demo'")
    op.execute("UPDATE tasks SET type = 'CUSTOM' WHERE type = 'custom'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert enum values to lowercase
    op.execute("UPDATE tasks SET type = 'route' WHERE type = 'ROUTE'")
    op.execute("UPDATE tasks SET type = 'carpet' WHERE type = 'CARPET'")
    op.execute("UPDATE tasks SET type = 'demo' WHERE type = 'DEMO'")
    op.execute("UPDATE tasks SET type = 'custom' WHERE type = 'CUSTOM'")
    
    op.execute("ALTER TABLE tasks MODIFY COLUMN type ENUM('route','carpet','demo','custom') NOT NULL")
    
    # ### end Alembic commands ###
