"""make_robot_name_nullable_in_tasks

Revision ID: 67692ae7e5be
Revises: 8f681827b456
Create Date: 2025-10-23 20:51:21.877941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67692ae7e5be'
down_revision = '8f681827b456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
