"""add geojson_filename to tasks

Revision ID: add_geojson_filename_to_tasks
Revises: c87f163e14f0
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_geojson_filename_to_tasks'
down_revision = 'c87f163e14f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('geojson_filename', sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'geojson_filename')
    # ### end Alembic commands ###
