"""make_robot_name_nullable_in_tasks_v2

Revision ID: c87f163e14f0
Revises: 67692ae7e5be
Create Date: 2025-10-23 20:51:46.227636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c87f163e14f0'
down_revision = '67692ae7e5be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'robot_name',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'robot_name',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
